// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reena.MSSQL.Models;

public partial class FavoriteActivity
{
    public int ActivityId { get; set; }

    public string ActivityName { get; set; }
}