// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Reena.MSSQL.Models;

public partial class SpokenLanguage
{
    public int SpokenLanguageId { get; set; }

    public string SpokenLanguageName { get; set; }
}